
ARG FLUENTD_BUILD_VERSION
FROM fluent/fluentd:${FLUENTD_BUILD_VERSION}

LABEL author="zero <sontt246@gmail.com>"

ARG FLUENTD_PLUGINS
ENV FLUENTD_PLUGINS=$FLUENTD_PLUGINS

RUN apk add --update --virtual .build-deps sudo build-base ruby-dev \
    && sudo gem install $FLUENTD_PLUGINS \
    && sudo gem sources --clear-all \
    && apk del .build-deps \
    && rm -rf /var/cache/apk/* /home/fluent/.gem/ruby/2.3.0/cache/*.gem

